/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.32
 * Generated at: 2023-06-01 08:19:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import util.*;
import bean.*;

public final class fqa_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/common/footer.jsp", Long.valueOf(1685414785045L));
    _jspx_dependants.put("/common/userHeader.jsp", Long.valueOf(1685500090460L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("util");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("bean");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<title>お問い合わせフォーム</title>\r\n");
      out.write("\t\t<link rel =\"stylesheet\" href =\"");
      out.print( request.getContextPath() );
      out.write("/css/style.css\">\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<ul class=\"menu user\">\r\n");
      out.write("\t<li><div><a href=\"");
      out.print( request.getContextPath() );
      out.write("/view/userInputForm.jsp\"><i class=\"fa-solid fa-house\" style=\"color: #5bc8ac;\"></i><br>ホーム</a></div>\r\n");
      out.write("\t<li><div><a href=\"");
      out.print( request.getContextPath() );
      out.write("/view/fqa.jsp\"><i class=\"fa-solid fa-comments\" style=\"color: #5bc8ac;\"></i><br>よくある質問</a></div>\r\n");
      out.write("</ul>\r\n");
      out.write("\r\n");
      out.write("<h1>神田英会話スクール</h1>");
      out.write("\r\n");
      out.write("\t\t<h2>よくあるご質問</h2>\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<h2 class=\"headline\">\r\n");
      out.write("\t\t\t\t<span>01</span>\r\n");
      out.write("\t\t\t\tご入学までの流れ\r\n");
      out.write("\t\t\t</h2>\r\n");
      out.write("\t\t\t<details class=\"fqa\">\r\n");
      out.write("\t\t\t\t<summary class=\"fqa\">入学までの流れを教えてください。</summary>\r\n");
      out.write("\t\t\t\t<p>まずは各スクールで無料体験レッスン・コース説明会にご参加ください。\r\n");
      out.write("\t\t\t\tご希望を詳しくお聞きしながら、レッスン内容・担当教師・テキスト・時間割などを具体的にご案内いたします。\r\n");
      out.write("\t\t\t\tご不安な点をクリアにされてから、ご入学を検討いただけます。</p>\r\n");
      out.write("\t\t\t</details>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<details class=\"fqa\">\r\n");
      out.write("\t\t\t\t<summary class=\"fqa\">いつから始められますか？</summary>\r\n");
      out.write("\t\t\t\t<p>いつからでも始めていただけるようにカリキュラムを整えています。\r\n");
      out.write("\t\t\t\t早速明日からでも、来月からでも、ご都合に合わせて始めていただけます。</p>\r\n");
      out.write("\t\t\t</details>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<details class=\"fqa\">\r\n");
      out.write("\t\t\t\t<summary class=\"fqa\">どのコースが自分に合っているのか、よくわからないです。</summary>\r\n");
      out.write("\t\t\t\t<p>い一人ひとりの生徒様に適切なレッスンを提供できるように、コース、レベル、教材を豊富にご用意しております。\r\n");
      out.write("\t\t\t\t目的や目標レベル、ご予算やお時間のご都合に合わせて、コースをご紹介いたしますので、ぜひ、最寄のスクールの無料体験レッスン・コース説明会にご参加ください。</p>\r\n");
      out.write("\t\t\t</details>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<h2 class=\"headline\">\r\n");
      out.write("\t\t\t\t<span>02</span>\r\n");
      out.write("\t\t\t\t教師について\r\n");
      out.write("\t\t\t</h2>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<details class=\"fqa\">\r\n");
      out.write("\t\t\t\t<summary class=\"fqa\">先生は選べますか？</summary>\r\n");
      out.write("\t\t\t\t<p>はい、お選びいただけます。イーオンには外国人教師と日本人教師がおります。\r\n");
      out.write("\t\t\t\t目的やレベルに合わせてどちらの教師が良いかご提案さしあげますが、最初は外国人教師で始めたけれど、日本人教師に習ってみたいなど、途中で担当教師を変更したいというご相談も承ります。</p>\r\n");
      out.write("\t\t\t</details>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<h2 class=\"headline\">\r\n");
      out.write("\t\t\t\t<span>03</span>\r\n");
      out.write("\t\t\t\t費用について\r\n");
      out.write("\t\t\t</h2>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<details class=\"fqa\">\r\n");
      out.write("\t\t\t\t<summary class=\"fqa\">授業料はいくらですか？</summary>\r\n");
      out.write("\t\t\t\t<p>週1回、1年間のコースの場合、1ヶ月あたり〇〇円（税込）です。\r\n");
      out.write("\t\t\t\tそのほか目標別に、様々なタイプのコースがございます。\r\n");
      out.write("\t\t\t\tご予算に合せてコースをご提案させていただいております。\r\n");
      out.write("\t\t\t\t代表的な授業料に関しては、各スクールページからご覧いただけます。</p>\r\n");
      out.write("\t\t\t</details>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<details class=\"fqa\">\r\n");
      out.write("\t\t\t\t<summary class=\"fqa\">支払い方法にはどのようなものがありますか？</summary>\r\n");
      out.write("\t\t\t\t<p><b>一括払いの場合：</b><br>\r\n");
      out.write("\t\t\t\t\t銀行振り込み・コンビニ振込み・クレジットカード・デビットカード（加盟銀行のキャッシュカード）\r\n");
      out.write("\t\t\t\t\t<br><br>\r\n");
      out.write("\t\t\t\t\t<b>分割払いの場合：</b><br>\r\n");
      out.write("\t\t\t\t\tイーオンスチューデントクレジットをご利用いただくと、月々払いが可能です。＊分割手数料がかかります。</p>\r\n");
      out.write("\t\t\t</details>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<h2 class=\"headline\">\r\n");
      out.write("\t\t\t\t<span>04</span>\r\n");
      out.write("\t\t\t\tその他\r\n");
      out.write("\t\t\t</h2>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<details class=\"fqa\">\r\n");
      out.write("\t\t\t\t<summary class=\"fqa\">どのような感染対策をしていますか？</summary>\r\n");
      out.write("\t\t\t\t<p>生徒様の安心してお通いいただけるよう、各教室では衛生面対策の取り組みを行っております。</p>\r\n");
      out.write("\t\t\t</details>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<details class=\"fqa\">\r\n");
      out.write("\t\t\t\t<summary class=\"fqa\">英語は苦手で全く初めてですが、大丈夫ですか？</summary>\r\n");
      out.write("\t\t\t\t<p>もちろん、大丈夫です。ほとんどの方が英会話は初めてでいらっしゃいます。\r\n");
      out.write("\t\t\t\t学生のときに学んだ英語も、普段使わないと忘れてしまうものです。\r\n");
      out.write("\t\t\t\tそのような日本人学習者の方向けに作られたオリジナルテキストを使っていくことで少しずつ自然に思い出していただけますのでご安心下さい。</p>\r\n");
      out.write("\t\t\t</details>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<form action=\"");
      out.print( request.getContextPath() );
      out.write("/view/userInputForm.jsp\">\r\n");
      out.write("\t\t\t\t<input class=\"send\" type=\"submit\" value=\"お問い合わせする\">\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<hr class=\"greenLine\">\r\n");
      out.write("<h4 class=\"footer\">copyright (c) 2023 all rights reserved.</h4>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
