/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.32
 * Generated at: 2023-06-01 07:46:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import util.*;

public final class userInputForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/common/footer.jsp", Long.valueOf(1685414785045L));
    _jspx_dependants.put("/common/userHeader.jsp", Long.valueOf(1685500090460L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("util");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

request.setCharacterEncoding("utf-8");
String name = Converter.getParam(request.getParameter("name"));
String readname = Converter.getParam(request.getParameter("readname"));
String age = Converter.getParam(request.getParameter("age"));
String sex = Converter.getParam(request.getParameter("sex"));
String email = Converter.getParam(request.getParameter("email"));
String tel1st = Converter.getParam(request.getParameter("tel1st"));
String tel2nd = Converter.getParam(request.getParameter("tel2nd"));
String tel3rd = Converter.getParam(request.getParameter("tel3rd"));
String addcode1st = Converter.getParam(request.getParameter("addcode1st"));
String addcode2nd = Converter.getParam(request.getParameter("addcode2nd"));
String pref = Converter.getParam(request.getParameter("pref"));
String city = Converter.getParam(request.getParameter("city"));
String other = Converter.getParam(request.getParameter("other"));
String contenttype = Converter.getParam(request.getParameter("contenttype"));
String content = Converter.getParam(request.getParameter("content"));

String personalInformation = "神田英会話スクール（以下、当スクール）では、お預かりした個人情報について、以下のとおり適正かつ安全に管理・運用することに努めます。\n\n"
	+ "１．利用目的\n\n"
	+ "当スクールは、収集した個人情報について、以下の目的のために利用いたします。\n"
	+ "①商品発送やサービス実施、およびアフターサービスのため\n"
	+ "②資料請求に対する発送のため\n"
	+ "③相談・お問い合わせへの回答のため\n\n\n"
	+ "２．第三者提供\n\n"
	+ "当スクールは、以下の場合を除いて、個人データを第三者へ提供することはしません。\n"
	+ "①法令に基づく場合\n"
	+ "②人の生命・身体・財産を保護するために必要で、本人から同意を得ることが難しい場合\n"
	+ "③公衆衛生の向上・児童の健全な育成のために必要で、本人から同意を得ることが難しい場合\n"
	+ "④国の機関や地方公共団体、その委託者などによる法令事務の遂行にあたって協力する必要があり、\n"
	+ "かつ本人の同意を得ることで事務遂行に影響が生じる可能性がある場合\n\n\n"
	+ "３．開示請求\n\n"
	+ "貴殿の個人情報について、ご本人には、開示・訂正・削除・利用停止を請求する権利があります。\n"
	+ "手続きにあたっては、ご本人確認のうえ対応させていただきますが、代理人の場合も可能です。\n\n\n\n";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<title>お問い合わせフォーム</title>\r\n");
      out.write("\t\t<link rel =\"stylesheet\" href =\"");
      out.print( request.getContextPath() );
      out.write("/css/style.css\">\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<ul class=\"menu user\">\r\n");
      out.write("\t<li><div><a href=\"");
      out.print( request.getContextPath() );
      out.write("/view/userInputForm.jsp\"><i class=\"fa-solid fa-house\" style=\"color: #5bc8ac;\"></i><br>ホーム</a></div>\r\n");
      out.write("\t<li><div><a href=\"");
      out.print( request.getContextPath() );
      out.write("/view/fqa.jsp\"><i class=\"fa-solid fa-comments\" style=\"color: #5bc8ac;\"></i><br>よくある質問</a></div>\r\n");
      out.write("</ul>\r\n");
      out.write("\r\n");
      out.write("<h1>神田英会話スクール</h1>");
      out.write("\r\n");
      out.write("\t\t<h2>お問い合わせフォーム</h2>\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<form action=\"");
      out.print( request.getContextPath() );
      out.write("/view/userCheckForm.jsp\" method=\"post\">\r\n");
      out.write("\t\t\t\t<h3><font color=\"red\">※入力欄は全て必須です</font><br>よくある質問もご確認ください</h3>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<ol class=\"timeline\">\r\n");
      out.write("\t\t\t\t\t<li class=\"current\">STEP1:お問い合わせ内容入力</li>\r\n");
      out.write("\t\t\t\t\t<li>STEP2:入力内容確認</li>\r\n");
      out.write("\t\t\t\t\t<li>STEP3:送信完了</li>\r\n");
      out.write("\t\t\t\t</ol>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<p class=\"label\">■お客様情報</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"formItem user\">\r\n");
      out.write("\t\t\t\t\t<p class=\"label\"><span class=\"labelRequired\">必須</span>氏名</p>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"name\" value=\"");
      out.print( name );
      out.write("\" required>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"formItem user\">\r\n");
      out.write("\t\t\t\t\t<p class=\"label\"><span class=\"labelRequired\">必須</span>ふりがな</p>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"readname\" value=\"");
      out.print( readname );
      out.write("\" required>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"formItem user\">\r\n");
      out.write("\t\t\t\t\t<p class=\"label\"><span class=\"labelRequired\">必須</span>年齢</p>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"age\" value=\"");
      out.print( age );
      out.write("\" required>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"formItem user\">\r\n");
      out.write("\t\t\t\t\t<p class=\"label\"><span class=\"labelRequired\">必須</span>性別</p>\r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"sex\" id=\"man\" value=\"男\" required");
if (sex.equals("男"))out.print(" checked");
      out.write("><label for=\"man\" class=\"sex\">男</label>\r\n");
      out.write("\t\t\t\t\t<input type=\"radio\" name=\"sex\" id=\"woman\" value=\"女\" required");
if (sex.equals("女"))out.print(" checked");
      out.write("><label for=\"woman\" class=\"sex\">女</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"formItem user\">\r\n");
      out.write("\t\t\t\t\t<p class=\"label\"><span class=\"labelRequired\">必須</span>メールアドレス</p>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"email\" value=\"");
      out.print( email );
      out.write("\" required>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"formItem user tel\">\r\n");
      out.write("\t\t\t\t\t<p class=\"label\"><span class=\"labelRequired\">必須</span>電話番号</p>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"tel1st\" value=\"");
      out.print( tel1st );
      out.write("\" maxlength=\"4\" required>&nbsp;<b>-</b>&nbsp;\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"tel2nd\" value=\"");
      out.print( tel2nd );
      out.write("\" maxlength=\"4\" required>&nbsp;<b>-</b>&nbsp;\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"tel3rd\" value=\"");
      out.print( tel3rd );
      out.write("\" maxlength=\"4\" required>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<p class=\"label\">■住所</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"formItem user addcode\">\r\n");
      out.write("\t\t\t\t\t<p class=\"label\"><span class=\"labelRequired\">必須</span>郵便番号</p>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"addcode1st\" value=\"");
      out.print( addcode1st );
      out.write("\" maxlength=\"3\" required>&nbsp;<b>-</b>&nbsp;\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"addcode2nd\" value=\"");
      out.print( addcode2nd );
      out.write("\" maxlength=\"4\" required>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"formItem user\">\r\n");
      out.write("\t\t\t\t\t<p class=\"label\"><span class=\"labelRequired\">必須</span>都道府県</p>\r\n");
      out.write("\t\t\t\t\t<select name=\"pref\" id=\"pref\" required>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"\" hidden>選択してください</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"北海道\">北海道</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"青森県\">青森県</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"岩手県\">岩手県</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"宮城県\">宮城県</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"秋田県\">秋田県</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"山形県\">山形県</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"福島県\">福島県</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"茨城県\">茨城県</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"栃木県\">栃木県</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"群馬県\">群馬県</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"埼玉県\">埼玉県</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"千葉県\">千葉県</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"東京都\">東京都</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"神奈川県\">神奈川県</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"新潟県\">新潟県</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"富山県\">富山県</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"石川県\">石川県</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"福井県\">福井県</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"山梨県\">山梨県</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"長野県\">長野県</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"岐阜県\">岐阜県</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"静岡県\">静岡県</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"愛知県\">愛知県</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"三重県\">三重県</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"滋賀県\">滋賀県</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"京都府\">京都府</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"大阪府\">大阪府</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"兵庫県\">兵庫県</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"奈良県\">奈良県</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"和歌山県\">和歌山県</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"鳥取県\">鳥取県</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"島根県\">島根県</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"岡山県\">岡山県</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"広島県\">広島県</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"山口県\">山口県</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"徳島県\">徳島県</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"香川県\">香川県</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"愛媛県\">愛媛県</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"高知県\">高知県</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"福岡県\">福岡県</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"佐賀県\">佐賀県</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"長崎県\">長崎県</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"熊本県\">熊本県</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"大分県\">大分県</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"宮崎県\">宮崎県</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"鹿児島県\">鹿児島県</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"沖縄県\">沖縄県</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"formItem user\">\r\n");
      out.write("\t\t\t\t\t<p class=\"label\"><span class=\"labelRequired\">必須</span>市区町村</p>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"city\" value=\"");
      out.print( city );
      out.write("\" required>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"formItem user\">\r\n");
      out.write("\t\t\t\t\t<p class=\"label\"><span class=\"labelRequired\">必須</span>以降の住所</p>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"other\" value=\"");
      out.print( other );
      out.write("\" required>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<p class=\"label\">■お問い合わせ詳細</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"formItem user\">\r\n");
      out.write("\t\t\t\t\t<p class=\"label\"><span class=\"labelRequired\">必須</span>お問い合わせ項目</p>\r\n");
      out.write("\t\t\t\t\t<span class=\"type\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=\"contenttype\" id=\"fee\" value=\"料金・お支払いについて\" required");
if (contenttype.equals("料金・お支払いについて"))out.print(" checked");
      out.write("><label for=\"fee\" class=\"type\">料金・お支払いについて</label><br><br>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=\"contenttype\" id=\"course\" value=\"講座・コース・教材について\" required");
if (contenttype.equals("講座・コース・教材について"))out.print(" checked");
      out.write("><label for=\"course\" class=\"type\">講座・コース・教材について</label><br><br>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=\"contenttype\" id=\"proceed\" value=\"学習の進め方について\" required");
if (contenttype.equals("学習の進め方について"))out.print(" checked");
      out.write("><label for=\"proceed\" class=\"type\">学習の進め方について</label><br><br>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=\"contenttype\" id=\"term\" value=\"受講期間について\" required");
if (contenttype.equals("受講期間について"))out.print(" checked");
      out.write("><label for=\"term\" class=\"type\">受講期間について</label><br><br>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=\"contenttype\" id=\"support\" value=\"受講終了後のサポートについて\" required");
if (contenttype.equals("受講終了後のサポートについて"))out.print(" checked");
      out.write("><label for=\"support\" class=\"type\">受講終了後のサポートについて</label><br><br>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=\"contenttype\" id=\"other\" value=\"その他お問い合わせ\" required");
if (contenttype.equals("その他お問い合わせ"))out.print(" checked");
      out.write("><label for=\"other\" class=\"type\">その他お問い合わせ</label><br><br>\r\n");
      out.write("\t\t\t\t\t</span>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"formItem user\">\r\n");
      out.write("\t\t\t\t\t<p class=\"label\"><span class=\"labelRequired\">必須</span>お問い合わせ内容</p>\r\n");
      out.write("\t\t\t\t\t<textarea class=\"userinput\" name=\"content\" rows=\"10\" cols=\"50\" required>");
      out.print( content );
      out.write("</textarea>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"personalInformation\">\r\n");
      out.write("\t\t\t\t\t<div>個人情報の取り扱いについて</div>\r\n");
      out.write("\t\t\t\t\t<p>");
      out.print( personalInformation );
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t<fieldset class=\"consent\">\r\n");
      out.write("\t\t\t\t\t\t\t<label><input type=\"radio\" name=\"consent\" value=\"disagree\" checked required><b>同意しない</b></label>\r\n");
      out.write("\t\t\t\t\t\t\t<label><input type=\"radio\" name=\"consent\" value=\"agree\" required><font color=\"red\"><b>同意する</b></font></label>\r\n");
      out.write("\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<input class=\"send\" type=\"submit\" value=\"送信内容確認\">\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<hr class=\"greenLine\">\r\n");
      out.write("<h4 class=\"footer\">copyright (c) 2023 all rights reserved.</h4>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\twindow.addEventListener(\"load\", function() {\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"pref\").value=\"");
      out.print( pref );
      out.write("\";\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
